wsgi/myproject/accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^all-users/$', views.all_users, name='all-users'),
    url(r'^adduser/$', views.add_user, name='add_user'),
    url(r'^edit_user/(?P<user_id>\d+)/$', views.edit_user, name='edit_user'),
    url(r'^delete_user/(?P<user_id>\d+)/$', views.delete_user, name='delete_user'),
    url(r'^get_user_by_id/(?P<user_id>\d+)/$', views.get_user_by_id, name='get_user_by_id'),
    url(r'^get_user_query/(?P<query>\w+)/$', views.get_user_query, name='get_user_query'),
]

wsgi/myproject/myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^admin/', include(admin.site.urls)),
]

wsgi/myproject/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User

# install by pip install django-fernet-fields


# Create your models here.
class MyUser(AbstractUser):
    """Description: Model Description."""

    function = models.CharField(max_length=150, default='shop')

    class Meta:
        """Description: Meta."""

        db_table = 'auth_user'
        unique_together = ('email',)
        User._meta.get_field('username')._unique = False

wsgi/myproject/accounts/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib.auth import(
    authenticate, login as auth_login,
    logout as auth_logout
)
from django.db.models import Q

from django.shortcuts import redirect
from .models import MyUser

import json
from django.http import JsonResponse


def create_response_user(users_query):
    users = []
    for user in users_query:
        users.append({
            'id': user.id,
            'first_name': user.first_name,
            'last_name': user.last_name,
            'email': user.email,
            'permission': user.function,
        })
    return users


def login(request):
    message = ''
    user = []
    if request.method == 'POST':
        email = request.POST.get('login')
        password = request.POST.get('password')
        try:
            user = MyUser.objects.get(email=email)
        except:
            pass
        if user != []:
            user = authenticate(username=user.username, password=password)
            if user is not None:
                if user.is_active:
                    auth_login(request, user)
                    return redirect('/')
        message = "Email de Usuario o Contraseña no válido"
        return render(request, 'intra/login.html', {'message': message, 'success': True})
    return render(request, 'login.html', {'message': message, 'success': False})


def logout(request):
    """Sistem logout."""
    auth_logout(request)
    return redirect('/')


@login_required(login_url='login/')
def index(request):
    return render(request, 'users.html')


def all_users(request):
    response = {}
    response['users'] = []
    users = MyUser.objects.all().order_by('id')
    response['users'] = create_response_user(users)
    return JsonResponse(response)


def add_user(request):
    message = 'Ok'
    data = request.POST.get('model')
    data = json.loads(data)

    email = data['email']
    if email and MyUser.objects.filter(email=email).count():
        message = 'El Email ya se encuenta registrado.\n'
    else:
        user = MyUser(
            username=data['email'],
            first_name=data['first_name'],
            last_name=data['last_name'],
            email=data['email'],
            function=data['permission'],
            password=data['password'],
        )
        user.save()
        user.set_password(data['password'])
        user.save()

    return JsonResponse({'success': message})


def edit_user(request, user_id):
    message = 'Ok'
    data = request.POST.get('model')
    data = json.loads(data)
    user = MyUser.objects.get(id=user_id)

    email = data['email']
    if data['email'] != user.email:
        if email and MyUser.objects.filter(email=email).count():
            message = 'Email ya se encuenta registrado.\n'
            return JsonResponse({'status': message})
        user.username = user.email = data['email']

    if data['password'] != 'no_pass':
        user.set_password(data['password'])
    if data['first_name'] != user.first_name:
        user.first_name = data['first_name']
    if data['last_name'] != user.last_name:
        user.last_name = data['last_name']
    if data['permission'] != user.function:
        user.function = data['permission']
    user.save()

    return JsonResponse({'status': message})


def delete_user(request, user_id):
    print "Id a eliminar: ", user_id
    user = MyUser.objects.get(id=user_id)
    user.delete()

    return JsonResponse({'status': 'Ok'})


def get_user_by_id(request, user_id):
    response = {}
    user = MyUser.objects.get(id=user_id)

    response['users'] = []
    response['users'].append({
        'id': user.id,
        'first_name': user.first_name,
        'last_name': user.last_name,
        'email': user.email,
        'permission': user.function,
    })
    return JsonResponse(response)


def get_user_query(request, query):
    response = {}
    response['users'] = []
    users = MyUser.objects.filter(Q(first_name__icontains=query) |
                                  Q(username__icontains=query) |
                                  Q(pk__icontains=query))
    print query
    if users != []:
        response['users'] = create_response_user(users)
        return JsonResponse(response)
    return JsonResponse(response)

wsgi/templates/base.html
{% load i18n admin_static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-datetimepicker.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/metisMenu.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/timeline.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/morris.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/sb-admin-2.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/font-awesome.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/fileinput.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/typeaheadjs.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/chosen.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/app.css" %}" />
{% block extrastyle %}{% endblock %}
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% block stylesheet_ie %}{% static "admin/css/ie.css" %}{% endblock %}" /><![endif]-->

{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}
<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

<!-- Container -->
<div class="wrapper">
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                {% block branding %}{% endblock %}
            </div>

            
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{% url "accounts:logout" %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <div class="navbar-default sidebar" role="navigation" id="sidebar">
                <div class="sidebar-nav navbar-collapse">
                    <ul id="side-menu" class="nav">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input id="search" class="form-control" type="text" placeholder="Buscar..."/>
                                <span class="input-group-btn">
                                    <button class="btn btn-default">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </li>
                        {% if user.function == 'admin'%}
                        <li>
                            <a href="{% url "accounts:index" %}"><i class="fa fa-user fa-fw"></i> Usuarios</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div id="page-wrapper" class="row">
                    {% block messages %}
                        {% if messages %}
                        <ul class="messagelist">
                            {% for message in messages %}
                              <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    {% endblock messages %}
                    <!-- Content -->
                    {% block content %}

                    {% endblock %}
                    <!-- END Content -->
                    {% block footer %}<div id="footer"></div>{% endblock %}

        </div>
</div>
<!-- END Container -->
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/moment.min.js" %}"></script>
    <script src="{% static "js/underscore-min.js" %}"></script>
    <script src="{% static "js/backbone-min.js" %}"></script>
    <script src="{% static "js/backbone.localStorage.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/raphael-min.js" %}"></script>
    <script src="{% static "js/morris.min.js" %}"></script>
    <script src="{% static "js/metisMenu.min.js" %}"></script>
    <script src="{% static "js/sb-admin-2.js" %}"></script>
    <script src="{% static "js/fileinput.js" %}"></script>
    <script src="{% static "js/typeahead.bundle.js" %}"></script>
    <script src="{% static "js/bootstrap-datetimepicker.min.js" %}"></script>
    <script src="{% static "js/chosen.jquery.js" %}"></script>
    <script src="{% static "js/app.js" %}"></script>
    <script src="{% static "js/fileinput/fileinput.js" %}"></script>
    <script src="{% static "js/fileinput/fileinput_locale_es.js" %}"></script>
    {% block extra_scripts %} {% endblock %}
</body>
</html>

wsgi/templates/base_site.html
{% extends "base.html" %}

{% block title %} Administración IntraG8 {% endblock %}

{% block branding %}
<a class="navbar-brand" href="{% url 'accounts:index' %}">Administración App-G8</a>
{% endblock %}

{% block nav-global %}{% endblock %}

wsgi/templates/index.html
{% extends "base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %} {% endblock %}

{% block coltype %} {% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
    <!-- Contend Here -->
{% endblock %}

{% block extra_scripts %}

{% endblock extra_scripts %}

{% block sidebar %}

{% endblock %}

wsgi/templates/login.html
{% load i18n staticfiles %}<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>IntraG8</title>

    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" />
    <link href="{% static "css/metisMenu.min.css" %}" rel="stylesheet" />
    <link href="{% static "css/sb-admin-2.css" %}" rel="stylesheet">
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Por favor ingrese al sistema</h3>
                    </div>
                    <div class="panel-body">
                        {% if success %}
                        <div>
                            <div class="alert alert-danger" role="alert">{{ message }}</div>
                        </div>
                        {% endif %}
                        <form action="{% url 'accounts:login' %}" method="POST">
                            {% csrf_token %} 
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" type="text" placeholder="Email" name="login" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" type="password" placeholder="Contraseña" name="password" value="">
                                </div>
                                <input type="hidden" value="#" name='current'>
                                <button class="btn btn-lg btn-success btn-block">Ingresar</button>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/metisMenu.min.js" %}"></script>
    <script src="{% static "js/sb-admin-2.js" %}"></script>
</body>
</html>

wsgi/templates/users.html
{% extends "base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %} {% endblock %}

{% block coltype %} {% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
    <!-- Contend Here -->
    <div class="row">
	    <div class="col-lg-12">
	        <h2 class="page-header">Usuarios</h2>
	    </div>
	</div>
	<div class="row">
	    <div class="col-md-10">
	        <div class="form-group input-group">
	            <input id="searchbox" type="text" class="form-control" placeholder="Buscar Usuarios...">
	            <span class="input-group-btn">
	                <button id="searchbutton" class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
	            </span>
	        </div>
	    </div>
	    <div class="col-md-2">
	        <button class="btn btn-primary btn-block btn-outline" data-toggle="modal" data-target="#addUserModal"><i class="fa fa-plus"></i> Agregar Usuario</button>
	    </div>
	</div>
	<div class="row">
	    <table class="table table-hover table-striped table-bordered">
	        <thead>
	            <tr>
	                <th>id</th>
	                <th>Nombre</th>
	                <th>Apellido</th>
	                <th>Email</th>
	                <th>Función</th>
	                <th>Operaciones</th>
	            </tr>
	        </thead>
	        <tbody id="user-table-body"></tbody>
	    </table>
	</div>

	<div id="addUserModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="saleModal" aria-hidden="true">
	  <div class="modal-dialog modal-md">
      <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Agregar Usuario</h4>
        </div>
		    <form action="#" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
	        <div class="modal-body">
						<div class="form-group">
						    <label for="add_product_id">Nombre</label>
						    <input type="text" class="form-control" id="add_user_first_name" name="add_user_first_name" placeholder="Nombre">
						</div>
						<div class="form-group">
						    <label for="add_ean">Apellido</label>
						    <input type="text" class="form-control" id="add_user_last_name" name="add_user_last_name" placeholder="Apellido">
						</div>
						<div class="form-group">
						    <label for="add_name">Email</label>
						    <input type="text" class="form-control" id="add_email" name="add_email" placeholder="Email">
						</div>
						<div class="form-group">
						    <label for="add_name">Contraseña</label>
						    <input type="text" class="form-control" id="add_password" name="add_password" placeholder="Contraseña">
						</div>
						<div class="form-group">
						    <label for="add_permission">Función</label>
						    <select id="add_permission" class="form-control" name="add_permission">
									<option value="no_select"> - Selecciones una Función - </option>
									<option value="admin"> Admin</option>
									<option value="administration"> Administración</option>
									<option value="shop"> Compras</option>
									<option value="management"> Gerencia</option>
									<option value="logistic"> Logística</option>
									<option value="sales"> Ventas</option>
						    </select>
						</div>
		    	</div>
	            <div class="modal-footer">
	                <button class="btn btn-default" type="button" data-dismiss="modal">Cerrar</button>
	                <button class="btn btn-success" type="button" onClick="user_add_user_modal_save();">Guardar</button>
	            </div>
	      </form>
	    </div>
	  </div>

	</div>
	<div id="editUserModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="saleModal" aria-hidden="true">
	    <div class="modal-dialog modal-md">
	      <div class="modal-content">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Editar Usuario</h4>
          </div>
	        <div class="modal-body">
						<div class="form-group">
						    <label for="add_product_id">Nombre</label>
						    <input type="text" class="form-control" id="edit_user_first_name" name="edit_user_first_name" placeholder="Nombre">
						</div>
						<div class="form-group">
						    <label for="add_ean">Apellido</label>
						    <input type="text" class="form-control" id="edit_user_last_name" name="edit_user_last_name" placeholder="Apellido">
						</div>
						<div class="form-group">
						    <label for="add_name">Email</label>
						    <input type="text" class="form-control" id="edit_email" name="edit_email" placeholder="Email">
						</div>
						<div class="form-group">
						    <label for="add_name">Contraseña</label>
						    <input type="text" class="form-control" id="edit_password" name="edit_password" placeholder="Contraseña">
						</div>
						<div class="form-group">
						    <label for="edit_permission">Función</label>
						    <select id="edit_permission" class="form-control" name="edit_permission">
									<option value="no_select"> - Selecciones una Función - </option>
									<option value="admin"> Admin</option>
									<option value="administration"> Administración</option>
									<option value="shop"> Compras</option>
									<option value="manager"> Gerencia</option>
									<option value="logistic"> Logística</option>
									<option value="sales"> Ventas</option>
						    </select>
						</div>
		    	</div>
	        <div class="modal-footer">
	            <button class="btn btn-default" type="button" data-dismiss="modal">Cerrar</button>
							<button class="btn btn-success" type="button" onClick="" id="edit_save">Guardar</button>
	         </div>
	      </div>
	    </div>
	</div>

	<div id="modalOk" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="ModalOkLabel">
	    <div class="modal-dialog modal-sm" role="document">
	        <div class="modal-content">
	            <div class="modal-header">
	                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	                    <span aria-hidden="true">&times;</span>
	                </button>
	                <h4 id="OkTitle" class="modal-title"></h4>
	            </div>
	            <div class="modal-body" id="Ok_modal_check">
	            </div>
	            <div class="modal-footer">
	                <button id="Ok_button" class="btn btn-default" type="button" data-dismiss="modal" onclick="get_all_users()">Cerrar</button>
	            </div>
	        </div>
	    </div>
	</div>

{% endblock %}

{% block extra_scripts %}
	<script >
		$( document ).ready(function(){
			get_all_users();
			var csrfToken = "{{ csrf_token }}";
	    $(document).ajaxSend(function(e, xhr, settings) {
	        xhr.setRequestHeader('X-CSRFToken', csrfToken);
		  });
		});

		$('#searchbox').keyup(function(e) { 
            if (e.keyCode == 13) { user_search_users(); }
        });

        $('#searchbutton').click(function () { 
                user_search_users(); 
        });
	</script>    
{% endblock extra_scripts %}

{% block sidebar %}

{% endblock %}